### ISSUE TITLE
Double free during shutdown

### ISSUE THREAD

**Issue by BraveSirRobin** [php-memcached-dev/php-memcached#34]
I've come across a low-level error in the shutdown sequence when testing fault-tolerance.  I'm using Ubuntu 12.10, PHP 5.3.10, memcached extension 1.0.2-2, all PHP packages are installed via. APT.

Script to reproduce error:

```php
<?php

/**
 * Dev machine setup
 *   4 memcache instances running on the same VM running over a local bridge
 *   SSH key-less access set up using ssh-copy-id
 */


// Replace these with your cluster.
$servers = array(array('vm2.local', '11211'),
                 array('vm2.local', '11212'),
                 array('vm2.local', '11213'),
                 array('vm2.local', '11214'));

$mc = new Memcached;
foreach ($servers as $s) {
    $mc->addServer($s[0], $s[1]);
}


// This key must map to the server you remove in the next step
$key = 'NMgJg2Bz1Z2hfmrM0a6Zl4FVUq6vq774';

// Stop one of the servers
exec("ssh root@vm2.local sudo /etc/init.d/memcached stop a", $out, $ret);
if ($ret != 0) {
    throw new \RuntimeException("Failed to stop memcache server:\n" . implode("\n", $out), 2376);
}

$mc->set($key, "This is a test!");

$mc->getServerByKey($key);

echo "Test is complete\n";
```

Crashes with the following error:
> *** glibc detected *** /usr/bin/php: double free or corruption (fasttop): 0x00000000010c2e10

Here's a gdb backtrace:
```
(gdb) bt
#0  0x00007ffff5b83445 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5b86bab in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff5bc0e2e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff5bcb626 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff5c1ab58 in freeaddrinfo () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007fffec74b9ab in memcached_server_list_free () from /usr/lib/libmemcached.so.6
#6  0x00007fffec749e49 in memcached_free () from /usr/lib/libmemcached.so.6
#7  0x00007fffec95b782 in ?? () from /usr/lib/php5/20090626/memcached.so
#8  0x00000000006bf5ff in zend_objects_store_del_ref_by_handle_ex (handle=17323080, handlers=0x4467) at /build/buildd/php5-5.3.10/Zend/zend_objects_API.c:220
#9  0x00000000006bf623 in zend_objects_store_del_ref (zobject=0x109d4c8) at /build/buildd/php5-5.3.10/Zend/zend_objects_API.c:172
#10 0x000000000068bb21 in _zval_ptr_dtor (zval_ptr=0x4467) at /build/buildd/php5-5.3.10/Zend/zend_variables.h:35
#11 0x00000000006a672e in zend_hash_apply_deleter () at /build/buildd/php5-5.3.10/Zend/zend_hash.c:813
#12 0x00000000006a82e1 in zend_hash_reverse_apply (ht=0xdd40a8, apply_func=0x68b9e0 <zval_call_destructor>) at /build/buildd/php5-5.3.10/Zend/zend_hash.c:964
#13 0x000000000068bed1 in shutdown_destructors () at /build/buildd/php5-5.3.10/Zend/zend_execute_API.c:226
#14 0x000000000069a167 in zend_call_destructors () at /build/buildd/php5-5.3.10/Zend/zend.c:947
#15 0x00000000006470bd in php_request_shutdown (dummy=0x4467) at /build/buildd/php5-5.3.10/main/main.c:1618
#16 0x000000000042b8d5 in main (argc=32767, argv=0x7fffffffe3e4) at /build/buildd/php5-5.3.10/sapi/cli/php_cli.c:1367
```

Note that the error is in the PHP shutdown sequence, the PHP script completes before it crashes

**Comment by sodabrew** [comment]
Closing due to inactivity.
